/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 9fb3504669c402c3d004d5b1beb6de2cc6f52e5c */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Yaf_Config_Abstract_count, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_Yaf_Config_Abstract_rewind arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Abstract_current arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Abstract_next arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Abstract_valid arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Abstract_key arginfo_class_Yaf_Config_Abstract_count

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Yaf_Config_Abstract___isset, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

#define arginfo_class_Yaf_Config_Abstract___get arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Abstract_offsetGet arginfo_class_Yaf_Config_Abstract___isset

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Yaf_Config_Abstract_offsetSet, 0, 0, 2)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

#define arginfo_class_Yaf_Config_Abstract_offsetUnSet arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Abstract_offsetExists arginfo_class_Yaf_Config_Abstract___isset

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Yaf_Config_Abstract_get, 0, 0, 0)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

#define arginfo_class_Yaf_Config_Abstract_set arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Abstract_readonly arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Abstract_toArray arginfo_class_Yaf_Config_Abstract_count

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Yaf_Config_Simple___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, config_file)
	ZEND_ARG_INFO(0, section)
ZEND_END_ARG_INFO()

#define arginfo_class_Yaf_Config_Simple___isset arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Simple___set arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Simple_get arginfo_class_Yaf_Config_Abstract_get

#define arginfo_class_Yaf_Config_Simple_set arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Simple_readonly arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Simple_offsetGet arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Simple_offsetSet arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Simple_offsetUnSet arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Ini___construct arginfo_class_Yaf_Config_Simple___construct

#define arginfo_class_Yaf_Config_Ini___isset arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Ini_get arginfo_class_Yaf_Config_Abstract_get

#define arginfo_class_Yaf_Config_Ini_set arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Ini_readonly arginfo_class_Yaf_Config_Abstract_count

#define arginfo_class_Yaf_Config_Ini_offsetGet arginfo_class_Yaf_Config_Abstract___isset

#define arginfo_class_Yaf_Config_Ini_offsetSet arginfo_class_Yaf_Config_Abstract_offsetSet

#define arginfo_class_Yaf_Config_Ini___set arginfo_class_Yaf_Config_Abstract_offsetSet
