<!--
  View template for IndexController::indexAction.
  Yaf_View_Simple auto-renders views/<controller>/<action>.phtml (both
  names lowercased); variables passed via assign() become local
  variables in the template ($app_name, $name).

  The stylesheet, script and logo below are served straight from
  public/css/, public/js/ and public/img/ by the web server — the
  rewrite rules only forward requests that do not match a real file.
-->
<html>
<head>
<meta charset="utf-8">
<title><?=$app_name?> — powered by Yaf</title>
<link rel="stylesheet" href="/css/style.css">
<script src="/js/app.js" defer></script>
</head>
<body>

<header class="top">
  <img class="logo" src="/img/yaf-logo.jpg" alt="Yaf logo">
  <div>
    <h1>Yaf <?=$app_name?></h1>
    <div class="tagline">A skeleton application generated by Yaf Codes Generator</div>
  </div>
</header>

<nav class="top">
  <a href="/">Home</a>
  <a href="/index/index/user/id/1">Model demo</a>
  <a href="/index/demo">Error demo</a>
</nav>

<main class="content">
  <div class="card">
    <h2>Yaf — Yet Another Framework</h2>
    <p>
      Hello <?=$name?>! You are looking at a Yaf application generated
      by <code>yaf_cg</code>. Yaf is not "yet another PHP framework" —
      it is a <strong>C framework exposed through PHP</strong>: every
      class, every route match, every dispatch cycle runs in compiled
      C code instead of interpreted PHP, so the per-request overhead is
      measured in microseconds, not milliseconds.
    </p>
  </div>

  <div class="grid">
    <div class="card">
      <h2>C-native speed</h2>
      <p>
        There are no framework PHP files to <code>require</code> — the
        router, dispatcher and loader already live in the extension's
        shared memory. <code>new Yaf_Application()</code> is instant,
        which matters when bootstrap cost dominates high-traffic apps.
      </p>
    </div>
    <div class="card">
      <h2>Zero dependencies</h2>
      <p>
        No Composer, no class-file loading cascade, no vendor/
        directory. One <code>pecl install yaf</code> (or a compile) and
        this skeleton is all there is — local first, nothing external
        to break.
      </p>
    </div>
    <div class="card">
      <h2>The "Yet Another" family</h2>
      <p>
        Yaf pairs with <a href="https://github.com/laruence/yaconf">Yaconf</a>
        (shared-memory configuration), <a href="https://github.com/laruence/yac">Yac</a>
        (shared-memory cache) and <a href="https://github.com/laruence/yar">Yar</a>
        (concurrent RPC) — the same C-native design philosophy.
      </p>
    </div>
    <div class="card">
      <h2>What this skeleton shows</h2>
      <p>
        The <a href="/index/index/user/id/1">model demo page</a> loads records through
        <code>SampleModel</code> — a mock DAO with an in-memory "table",
        ready to be swapped for a real database driver. Everything else
        (bootstrap hooks, a plugin, routing, error handling) is
        explained in the comments of the generated files under
        <code>application/</code>.
      </p>
    </div>
  </div>
</main>

<footer class="bottom">
  served by Yaf — the C-implemented PHP framework<br>
  <a href="https://www.php.net/manual/en/book.yaf.php">Yaf manual</a> ·
  <a href="https://github.com/laruence/yaf">Yaf on GitHub</a> ·
  <a href="https://www.laruence.com/">Author homepage</a>
</footer>

</body>
</html>
