<!--
  View template for IndexController::userAction, auto-rendered from
  views/index/user.phtml. The $user array was passed in via assign();
  it comes from SampleModel (the mock DAO), or is a "not found" row
  when the id does not exist.
-->
<html>
<head>
<meta charset="utf-8">
<title>User #<?=$user["id"]?> — <?=$app_name?></title>
<link rel="stylesheet" href="/css/style.css">
<script src="/js/app.js" defer></script>
</head>
<body>

<header class="top">
  <img class="logo" src="/img/yaf-logo.jpg" alt="Yaf logo">
  <div>
    <h1>Yaf <?=$app_name?></h1>
    <div class="tagline">A skeleton application generated by Yaf Codes Generator</div>
  </div>
</header>

<nav class="top">
  <a href="/">Home</a>
  <a href="/index/index/user/id/1">Model demo</a>
  <a href="/index/demo">Error demo</a>
</nav>

<main class="content">
  <div class="card">
    <h2>User #<?=$user["id"]?></h2>
    <p>
      This page was reached through the default static route
      <code>/index/index/user/id/:id</code>; the record below was loaded
      by <code>SampleModel</code>.
    </p>
    <table class="records">
      <tr><th>ID</th><th>Name</th><th>Role</th></tr>
      <tr>
        <td><?=$user["id"]?></td>
        <td><?=$user["name"]?></td>
        <td><?=$user["role"]?></td>
      </tr>
    </table>
    <button id="visit">Visit another random user</button>
  </div>
</main>

<footer class="bottom">
  served by Yaf — the C-implemented PHP framework<br>
  <a href="https://www.php.net/manual/en/book.yaf.php">Yaf manual</a> ·
  <a href="https://github.com/laruence/yaf">Yaf on GitHub</a> ·
  <a href="https://www.laruence.com/">Author homepage</a>
</footer>

</body>
</html>
