<?php
/**
 * Yaf Classes signature generator
 *
 * Reflects over the loaded Yaf extension and dumps every class,
 * interface, method and parameter signature into a plain PHP file
 * (tools/ide/yaf_classes.php). That file is NOT meant to be executed or
 * included at runtime — it exists for IDEs: point PhpStorm / VSCode at
 * it (include path or stub directory) and you get code completion,
 * parameter hints and jump-to-definition for the C-implemented Yaf
 * classes, which otherwise have no PHP source for the IDE to read.
 *
 * Regenerate it whenever the extension's API changes:
 *   php -d extension=yaf.so tools/ide/yaf.php > tools/ide/yaf_classes.php
 * (add -d yaf.use_namespace=1 to generate the namespaced style)
 *
 * @author  Laruence
 * @date    2012-07-21 13:46
 * @version $Id$
 */

$useNamespace = (bool) ini_get("yaf.use_namespace");
$yafClassPrefix = sprintf("Yaf%s", $useNamespace ? "\\" : "_");
$classes = array_merge(get_declared_classes(), get_declared_interfaces());
foreach ($classes as $key => $value) {
    if (strncasecmp($value, $yafClassPrefix, 4)) {
        unset($classes[$key]);
    }
}

echo "<?php\n";
echo "/**\n";
echo " * Yaf API signatures for IDE code completion.\n";
echo " *\n";
echo " * Generated by tools/ide/yaf.php from the loaded Yaf extension; do not\n";
echo " * edit by hand and do not include at runtime. Register this file as\n";
echo " * a stub / include-path entry in your IDE to get completion and\n";
echo " * parameter hints for the C-implemented Yaf classes.\n";
echo " */\n\n";

/* Whether a default value is acceptable for a declared type, so the
 * generated stub stays valid PHP source (C arginfo is looser). */
function defaultMatchesType(ReflectionType $type, $default) {
    if ($type instanceof ReflectionNamedType) {
        switch ($type->getName()) {
            case "mixed":
                return true;
            case "bool":
                return is_bool($default);
            case "int":
                return is_int($default);
            case "float":
                return is_float($default) || is_int($default);
            case "string":
                return is_string($default);
            case "array":
                return is_array($default);
            case "null":
                return $default === NULL;
            default:
                return $default === NULL;
        }
    }
    foreach ($type instanceof ReflectionUnionType ? $type->getTypes() : array() as $t) {
        if (defaultMatchesType($t, $default)) {
            return true;
        }
    }
    return false;
}

foreach ($classes as $class_name) {
    $class = new ReflectionClass($class_name);
    $indent  = "";
    $backslash = false;

    if ($useNamespace && false !== ($backslash = strrpos($class_name, "\\"))) {
        $namespaceName  = substr($class_name, 0, $backslash);
        $class_name = substr($class_name, $backslash + 1);
        echo "namespace ", $namespaceName, " {\n";

        $indent = "\t";
    }

    $classAttributes = "";

    // Yaf_Session is registered final+abstract in C (singleton: no
    // inheritance, no instantiation); PHP source cannot spell both, so
    // "final" wins here — it carries the useful hint for IDEs.
    $emit_abstract_class = $class->isAbstract() && !$class->isFinal();

    if ($class->isInterface()) {
        $classAttributes .= "interface ";
    } else {
        if ($class->isFinal()) {
            $classAttributes .= "final ";
        } else if ($emit_abstract_class) {
            $classAttributes .= "abstract ";
        }

        $classAttributes .= "class ";
    }

    echo $indent, $classAttributes, $class_name;

    /* parent */
    $parent = $class->getParentClass();
    if ($parent) {
        echo " extends ", $parent->getName();
    }

    /* interface */
    $interfaces = $class->getInterfaceNames();
    if (count($interfaces)) {
        echo " implements ", join(", ", $interfaces);
    }
    echo " {\n";

    $indent .= "\t";
    /* constants */
    $constants = $class->getConstants();
    if (0 < count($constants)) {
      echo $indent, "/* constants */\n";

      foreach ($constants as $k => $v) {
           echo $indent, "const ", $k , " = ", var_export($v, true), ";\n";
      }
      echo "\n";
    }

    /* properties */
    $properties = $class->getProperties();
    if (0 < count($properties)) {
      echo $indent, "/* properties */\n";
      $values     = $class->getDefaultProperties();
      foreach ($properties as $p) {
          echo $indent;

          if ($p->isStatic()) {
              echo "static ";
          }

          if ($p->isPublic()) {
              echo "public ";
          } else if ($p->isProtected()) {
              echo "protected ";
          } else {
              echo "private ";
          }

          echo '$', $p->getName(), " = ";

          if (isset($values[$p->getName()])) {
              echo var_export($values[$p->getName()], true);
          } else {
              echo "NULL";
          }
          echo ";\n";
      }
      echo "\n";
    }

    /* methods */
    $methods = $class->getMethods();
    if (0 < count($methods)) {
      echo $indent, "/* methods */\n";

      foreach ($methods as $m) {
          $is_abstract = $m->isAbstract();
          $modifiers = Reflection::getModifierNames($m->getModifiers());

          if ($is_abstract) {
              // PHP 8 forbids the "abstract" keyword on interface methods,
              // and a non-abstract class cannot carry abstract methods;
              // drop the modifier in both cases. Only abstract classes
              // keep it (and the signature-only form).
              if ($class->isInterface()) {
                  $modifiers = array_diff($modifiers, array("abstract"));
              } else if (!$emit_abstract_class) {
                  $is_abstract = false;
                  $modifiers = array_diff($modifiers, array("abstract"));
              }
          }

          echo $indent;
          echo implode(' ', $modifiers);
          echo " function ", $m->getName(), "(";

          if ($is_abstract || $class->isInterface()) {
              // signature only, no body
              echo ");\n";
              continue;
          }

          $parameters = $m->getParameters();
          $number = count($parameters);
          $index  = 0;
          foreach ($parameters as $a) {
              $is_optional = $a->isOptional() && !$a->isVariadic();
              $default = NULL;
              if ($is_optional) {
                  $default = $a->isDefaultValueAvailable()
                      ? $a->getDefaultValue() : NULL;
              }

              if (($type = $a->getType())) {
                  $type_str = (string) $type;
                  if ($is_optional && $default === NULL && !$type->allowsNull()) {
                      // PHP 8 forbids implicit nullable ("string $x = NULL")
                      $type_str = ($type instanceof ReflectionNamedType)
                          ? "?" . $type_str : $type_str . "|null";
                  } else if ($is_optional && $default !== NULL
                             && !defaultMatchesType($type, $default)) {
                      // C arginfo may pair a type with a default it rejects
                      // (bool $replace = 0); widen to mixed so stubs parse
                      $type_str = "mixed";
                  }
                  echo $type_str, " ";
              }

              if ($a->isPassedByReference()) {
                  echo "&";
              }

              if ($a->isVariadic()) {
                  echo "...";
              }

              echo "$", $a->getName();

              if ($is_optional) {
                  echo " = ", var_export($default, true);
              }

              if (++$index < $number) {
                  echo ", ";
              }
          }

          echo ") {\n";
          echo $indent, "}\n";
      }
    }

    $indent = substr($indent, 0, -1);
    echo $indent, "}\n";

    if ($useNamespace && false !== $backslash) {
        echo "}\n\n";
    }
}
