<?php
/**
 * Yaf API signatures for IDE code completion.
 *
 * Generated by tools/ide/yaf.php from the loaded Yaf extension; do not
 * edit by hand and do not include at runtime. Register this file as
 * a stub / include-path entry in your IDE to get completion and
 * parameter hints for the C-implemented Yaf classes.
 */

namespace Yaf {
	final class Application {
		/* methods */
		public function __construct(array|string $config, ?string $environ = NULL) {
		}
		public function run() {
		}
		public function execute(mixed $callback) {
		}
		public static function app() {
		}
		public function environ() {
		}
		public function bootstrap() {
		}
		public function getConfig() {
		}
		public function getModules() {
		}
		public function getDispatcher() {
		}
		public function setAppDirectory(string $directory) {
		}
		public function getAppDirectory() {
		}
		public function getLastErrorNo() {
		}
		public function getLastErrorMsg() {
		}
		public function clearLastError() {
		}
		public static function getInstance() {
		}
	}
}

namespace Yaf {
	abstract class Bootstrap_Abstract {
	}
}

namespace Yaf {
	final class Dispatcher {
		/* methods */
		private function __construct() {
		}
		public function enableView() {
		}
		public function disableView() {
		}
		public function initView(string $templates_dir, ?array $options = NULL) {
		}
		public function setView(object $view) {
		}
		public function setRequest(object $request) {
		}
		public function setResponse(object $response) {
		}
		public function getApplication() {
		}
		public function getRouter() {
		}
		public function getResponse() {
		}
		public function getRequest() {
		}
		public function getDefaultModule() {
		}
		public function getDefaultController() {
		}
		public function getDefaultAction() {
		}
		public function setErrorHandler(mixed $callback, int $error_types = 0) {
		}
		public function setDefaultModule(string $module) {
		}
		public function setDefaultController(string $controller) {
		}
		public function setDefaultAction(string $action) {
		}
		public function returnResponse(bool $flag = false) {
		}
		public function autoRender(?bool $flag = NULL) {
		}
		public function flushInstantly(?bool $flag = NULL) {
		}
		public static function getInstance() {
		}
		public function dispatch(object $request) {
		}
		public function throwException(?bool $flag = NULL) {
		}
		public function catchException(?bool $flag = NULL) {
		}
		public function registerPlugin(object $plugin) {
		}
	}
}

namespace Yaf {
	final class Loader {
		/* methods */
		private function __construct() {
		}
		public function autoload($class_name) {
		}
		public static function getInstance($local_library_path = NULL, $global_library_path = NULL) {
		}
		public function registerLocalNamespace($namespace, $path = NULL) {
		}
		public function getLocalNamespace() {
		}
		public function clearLocalNamespace() {
		}
		public function isLocalName($class_name) {
		}
		public function getNamespacePath($class_name) {
		}
		public static function import($file) {
		}
		public function setLibraryPath($library_path, $is_global = NULL) {
		}
		public function getLibraryPath($is_global = NULL) {
		}
		public function registerNamespace($namespace, $path = NULL) {
		}
		public function getNamespaces() {
		}
	}
}

namespace Yaf {
	abstract class Request_Abstract {
		/* constants */
		const SCHEME_HTTP = 'http';
		const SCHEME_HTTPS = 'https';

		/* methods */
		public function isGet() {
		}
		public function isPost() {
		}
		public function isDelete() {
		}
		public function isPatch() {
		}
		public function isPut() {
		}
		public function isHead() {
		}
		public function isOptions() {
		}
		public function isCli() {
		}
		public function isXmlHttpRequest() {
		}
		public function getQuery(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRequest(?string $name = NULL, mixed $default = NULL) {
		}
		public function getPost(?string $name = NULL, mixed $default = NULL) {
		}
		public function getCookie(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRaw() {
		}
		public function getFiles(?string $name = NULL, mixed $default = NULL) {
		}
		public function get(string $name, mixed $default = NULL) {
		}
		public function getServer(?string $name = NULL, mixed $default = NULL) {
		}
		public function getEnv(?string $name = NULL, mixed $default = NULL) {
		}
		public function setParam(mixed $name, mixed $value = NULL) {
		}
		public function getParam(string $name, mixed $default = NULL) {
		}
		public function getParams() {
		}
		public function clearParams() {
		}
		public function getException() {
		}
		public function getModuleName() {
		}
		public function getControllerName() {
		}
		public function getActionName() {
		}
		public function setModuleName(string $module, bool $format_name = true) {
		}
		public function setControllerName(string $controller, bool $format_name = true) {
		}
		public function setActionName(string $action, bool $format_name = true) {
		}
		public function getMethod() {
		}
		public function getLanguage() {
		}
		public function setBaseUri(string $uir) {
		}
		public function getBaseUri() {
		}
		public function getRequestUri() {
		}
		public function setRequestUri(string $uir) {
		}
		final public function isDispatched() {
		}
		final public function setDispatched(bool $flag = true) {
		}
		final public function isRouted() {
		}
		final public function setRouted(bool $flag = true) {
		}
	}
}

namespace Yaf\Request {
	class Http extends Yaf\Request_Abstract {
		/* methods */
		public function __construct(?string $requestUri = NULL, ?string $baseUri = NULL) {
		}
		public function isGet() {
		}
		public function isPost() {
		}
		public function isDelete() {
		}
		public function isPatch() {
		}
		public function isPut() {
		}
		public function isHead() {
		}
		public function isOptions() {
		}
		public function isCli() {
		}
		public function isXmlHttpRequest() {
		}
		public function getQuery(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRequest(?string $name = NULL, mixed $default = NULL) {
		}
		public function getPost(?string $name = NULL, mixed $default = NULL) {
		}
		public function getCookie(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRaw() {
		}
		public function getFiles(?string $name = NULL, mixed $default = NULL) {
		}
		public function get(string $name, mixed $default = NULL) {
		}
		public function getServer(?string $name = NULL, mixed $default = NULL) {
		}
		public function getEnv(?string $name = NULL, mixed $default = NULL) {
		}
		public function setParam(mixed $name, mixed $value = NULL) {
		}
		public function getParam(string $name, mixed $default = NULL) {
		}
		public function getParams() {
		}
		public function clearParams() {
		}
		public function getException() {
		}
		public function getModuleName() {
		}
		public function getControllerName() {
		}
		public function getActionName() {
		}
		public function setModuleName(string $module, bool $format_name = true) {
		}
		public function setControllerName(string $controller, bool $format_name = true) {
		}
		public function setActionName(string $action, bool $format_name = true) {
		}
		public function getMethod() {
		}
		public function getLanguage() {
		}
		public function setBaseUri(string $uir) {
		}
		public function getBaseUri() {
		}
		public function getRequestUri() {
		}
		public function setRequestUri(string $uir) {
		}
		final public function isDispatched() {
		}
		final public function setDispatched(bool $flag = true) {
		}
		final public function isRouted() {
		}
		final public function setRouted(bool $flag = true) {
		}
	}
}

namespace Yaf\Request {
	class Simple extends Yaf\Request_Abstract {
		/* constants */
		const SCHEME_HTTP = 'http';
		const SCHEME_HTTPS = 'https';

		/* methods */
		public function __construct(?string $method = NULL, ?string $module = NULL, ?string $controller = NULL, ?string $action = NULL, ?array $params = NULL) {
		}
		public function isXmlHttpRequest() {
		}
		public function isGet() {
		}
		public function isPost() {
		}
		public function isDelete() {
		}
		public function isPatch() {
		}
		public function isPut() {
		}
		public function isHead() {
		}
		public function isOptions() {
		}
		public function isCli() {
		}
		public function getQuery(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRequest(?string $name = NULL, mixed $default = NULL) {
		}
		public function getPost(?string $name = NULL, mixed $default = NULL) {
		}
		public function getCookie(?string $name = NULL, mixed $default = NULL) {
		}
		public function getRaw() {
		}
		public function getFiles(?string $name = NULL, mixed $default = NULL) {
		}
		public function get(string $name, mixed $default = NULL) {
		}
		public function getServer(?string $name = NULL, mixed $default = NULL) {
		}
		public function getEnv(?string $name = NULL, mixed $default = NULL) {
		}
		public function setParam(mixed $name, mixed $value = NULL) {
		}
		public function getParam(string $name, mixed $default = NULL) {
		}
		public function getParams() {
		}
		public function clearParams() {
		}
		public function getException() {
		}
		public function getModuleName() {
		}
		public function getControllerName() {
		}
		public function getActionName() {
		}
		public function setModuleName(string $module, bool $format_name = true) {
		}
		public function setControllerName(string $controller, bool $format_name = true) {
		}
		public function setActionName(string $action, bool $format_name = true) {
		}
		public function getMethod() {
		}
		public function getLanguage() {
		}
		public function setBaseUri(string $uir) {
		}
		public function getBaseUri() {
		}
		public function getRequestUri() {
		}
		public function setRequestUri(string $uir) {
		}
		final public function isDispatched() {
		}
		final public function setDispatched(bool $flag = true) {
		}
		final public function isRouted() {
		}
		final public function setRouted(bool $flag = true) {
		}
	}
}

namespace Yaf {
	abstract class Response_Abstract implements Stringable {
		/* constants */
		const DEFAULT_BODY = 'content';

		/* methods */
		public function __construct() {
		}
		public function __toString() {
		}
		public function setBody($body, $name = NULL) {
		}
		public function appendBody($body, $name = NULL) {
		}
		public function prependBody($body, $name = NULL) {
		}
		public function clearBody($name = NULL) {
		}
		public function getBody(?string $name = NULL) {
		}
		public function response() {
		}
	}
}

namespace Yaf\Response {
	class Http extends Yaf\Response_Abstract implements Stringable {
		/* constants */
		const DEFAULT_BODY = 'content';

		/* methods */
		public function setHeader(string $name, string $value, mixed $replace = 0, int $response_code = 0) {
		}
		public function setAllHeaders(array $headers) {
		}
		public function getHeader(?string $name = NULL) {
		}
		public function clearHeaders() {
		}
		public function setRedirect(string $url) {
		}
		public function response() {
		}
		public function __construct() {
		}
		public function __toString() {
		}
		public function setBody($body, $name = NULL) {
		}
		public function appendBody($body, $name = NULL) {
		}
		public function prependBody($body, $name = NULL) {
		}
		public function clearBody($name = NULL) {
		}
		public function getBody(?string $name = NULL) {
		}
	}
}

namespace Yaf\Response {
	class Cli extends Yaf\Response_Abstract implements Stringable {
		/* constants */
		const DEFAULT_BODY = 'content';

		/* methods */
		public function __construct() {
		}
		public function __toString() {
		}
		public function setBody($body, $name = NULL) {
		}
		public function appendBody($body, $name = NULL) {
		}
		public function prependBody($body, $name = NULL) {
		}
		public function clearBody($name = NULL) {
		}
		public function getBody(?string $name = NULL) {
		}
		public function response() {
		}
	}
}

namespace Yaf {
	abstract class Controller_Abstract {
		/* methods */
		public function __construct() {
		}
		protected function render(string $tpl, ?array $parameters = NULL) {
		}
		protected function display(string $tpl, ?array $parameters = NULL) {
		}
		public function getRequest() {
		}
		public function getResponse() {
		}
		public function getView() {
		}
		public function getName() {
		}
		public function getModuleName() {
		}
		public function initView(?array $options = NULL) {
		}
		public function setViewpath(string $view_directory) {
		}
		public function getViewpath() {
		}
		public function forward(mixed $args1, mixed $args2 = NULL, mixed $args3 = NULL, mixed $args4 = NULL) {
		}
		public function redirect(string $url) {
		}
		public function getInvokeArgs() {
		}
		public function getInvokeArg(string $name) {
		}
	}
}

namespace Yaf {
	abstract class Action_Abstract extends Yaf\Controller_Abstract {
		/* properties */
		protected $_controller = NULL;

		/* methods */
		abstract public function execute();
		public function getController() {
		}
		public function getControllerName() {
		}
		public function __construct() {
		}
		protected function render(string $tpl, ?array $parameters = NULL) {
		}
		protected function display(string $tpl, ?array $parameters = NULL) {
		}
		public function getRequest() {
		}
		public function getResponse() {
		}
		public function getView() {
		}
		public function getName() {
		}
		public function getModuleName() {
		}
		public function initView(?array $options = NULL) {
		}
		public function setViewpath(string $view_directory) {
		}
		public function getViewpath() {
		}
		public function forward(mixed $args1, mixed $args2 = NULL, mixed $args3 = NULL, mixed $args4 = NULL) {
		}
		public function redirect(string $url) {
		}
		public function getInvokeArgs() {
		}
		public function getInvokeArg(string $name) {
		}
	}
}

namespace Yaf {
	abstract class Config_Abstract implements Iterator, Traversable, ArrayAccess, Countable {
		/* methods */
		public function get(?string $name = NULL) {
		}
		public function count() {
		}
		public function toArray() {
		}
		public function offsetUnset(mixed $name) {
		}
		public function rewind() {
		}
		public function current() {
		}
		public function key() {
		}
		public function next() {
		}
		public function valid() {
		}
		public function __isset(string $name) {
		}
		public function __get(string $name) {
		}
		public function offsetGet(mixed $name) {
		}
		public function offsetExists(mixed $name) {
		}
		abstract public function offsetSet();
		abstract public function set();
		abstract public function readonly();
	}
}

namespace Yaf\Config {
	final class Ini extends Yaf\Config_Abstract implements Countable, ArrayAccess, Traversable, Iterator {
		/* methods */
		public function __construct(array|string $config_file, ?string $section = NULL) {
		}
		public function get(?string $name = NULL) {
		}
		public function set(string $name, mixed $value) {
		}
		public function readonly() {
		}
		public function __set(mixed $name, mixed $value) {
		}
		public function offsetGet(mixed $name) {
		}
		public function offsetSet(mixed $name, mixed $value) {
		}
		public function count() {
		}
		public function toArray() {
		}
		public function offsetUnset(mixed $name) {
		}
		public function rewind() {
		}
		public function current() {
		}
		public function key() {
		}
		public function next() {
		}
		public function valid() {
		}
		public function __isset(string $name) {
		}
		public function __get(string $name) {
		}
		public function offsetExists(mixed $name) {
		}
	}
}

namespace Yaf\Config {
	final class Simple extends Yaf\Config_Abstract implements Countable, ArrayAccess, Traversable, Iterator {
		/* methods */
		public function __construct(array|string $config_file, ?string $section = NULL) {
		}
		public function set(string $name, mixed $value) {
		}
		public function readonly() {
		}
		public function offsetUnset(mixed $name) {
		}
		public function __set(string $name, mixed $value) {
		}
		public function offsetSet(mixed $name, mixed $value) {
		}
		public function get(?string $name = NULL) {
		}
		public function count() {
		}
		public function toArray() {
		}
		public function rewind() {
		}
		public function current() {
		}
		public function key() {
		}
		public function next() {
		}
		public function valid() {
		}
		public function __isset(string $name) {
		}
		public function __get(string $name) {
		}
		public function offsetGet(mixed $name) {
		}
		public function offsetExists(mixed $name) {
		}
	}
}

namespace Yaf\View {
	class Simple implements Yaf\View_Interface {
		/* methods */
		final public function __construct(string $tempalte_dir, ?array $options = NULL) {
		}
		public function get(?string $name = NULL) {
		}
		public function assign(mixed $name = NULL, mixed $default = NULL) {
		}
		public function render(string $tpl, ?array $tpl_vars = NULL) {
		}
		public function eval(string $tpl_str, ?array $vars = NULL) {
		}
		public function display(string $tpl, ?array $tpl_vars = NULL) {
		}
		public function assignRef(?string $name, mixed &$value) {
		}
		public function clear(?string $name = NULL) {
		}
		public function setScriptPath(string $template_dir) {
		}
		public function getScriptPath() {
		}
		public function __isset(string $name) {
		}
		public function __set(string $name, mixed $value) {
		}
		public function __get(string $name) {
		}
	}
}

namespace Yaf {
	final class Router {
		/* methods */
		public function __construct() {
		}
		public function addRoute(string $name, object $route) {
		}
		public function addConfig(object|array $config) {
		}
		public function route(object $request) {
		}
		public function getRoute(string $name) {
		}
		public function getRoutes() {
		}
		public function getCurrentRoute() {
		}
	}
}

namespace Yaf {
	final class Route_Static implements Yaf\Route_Interface {
		/* methods */
		public function match(string $uri) {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf\Route {
	final class Simple implements Yaf\Route_Interface {
		/* methods */
		public function __construct(string $module_name, string $controller_name, string $action_name) {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf\Route {
	final class Supervar implements Yaf\Route_Interface {
		/* methods */
		public function __construct(string $supervar_name) {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf\Route {
	final class Rewrite implements Yaf\Route_Interface {
		/* methods */
		public function __construct(string $match, array $route, ?array $verify = NULL) {
		}
		public function match(string $uri) {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf\Route {
	final class Regex implements Yaf\Route_Interface {
		/* methods */
		public function __construct(string $match, array $route, ?array $map = NULL, ?array $verify = NULL, ?string $reverse = NULL) {
		}
		public function match(string $uri) {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf\Route {
	final class Map implements Yaf\Route_Interface {
		/* methods */
		public function __construct(mixed $controller_prefer = 1, string $delimiter = '') {
		}
		public function route($request) {
		}
		public function assemble(array $info, ?array $query = NULL) {
		}
	}
}

namespace Yaf {
	abstract class Plugin_Abstract {
		/* methods */
		public function routerStartup(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function routerShutdown(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function dispatchLoopStartup(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function dispatchLoopShutdown(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function preDispatch(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function postDispatch(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
		public function preResponse(Yaf\Request_Abstract $request, Yaf\Response_Abstract $response) {
		}
	}
}

namespace Yaf {
	final class Registry {
		/* methods */
		private function __construct() {
		}
		public static function get(string $name) {
		}
		public static function has(string $name) {
		}
		public static function set(string $name, mixed $value) {
		}
		public static function del(string $name) {
		}
	}
}

namespace Yaf {
	final class Session implements Iterator, Traversable, ArrayAccess, Countable {
		/* methods */
		private function __construct() {
		}
		public static function getInstance() {
		}
		public function start() {
		}
		public function get(?string $name = NULL) {
		}
		public function has(string $name) {
		}
		public function set(string $name, mixed $value) {
		}
		public function del(string $name) {
		}
		public function count() {
		}
		public function clear() {
		}
		public function offsetGet(mixed $name) {
		}
		public function offsetSet(mixed $name, mixed $value) {
		}
		public function offsetExists(mixed $name) {
		}
		public function offsetUnSet(mixed $name) {
		}
		public function __get(string $name) {
		}
		public function __isset(string $name) {
		}
		public function __set(string $name, mixed $value) {
		}
		public function __unset(string $name) {
		}
		public function current() {
		}
		public function next() {
		}
		public function key() {
		}
		public function valid() {
		}
		public function rewind() {
		}
	}
}

namespace Yaf {
	class Exception extends Exception implements Throwable, Stringable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception {
	class StartupError extends Yaf\Exception implements Stringable, Throwable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception {
	class RouterFailed extends Yaf\Exception implements Stringable, Throwable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception {
	class DispatchFailed extends Yaf\Exception implements Stringable, Throwable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception {
	class LoadFailed extends Yaf\Exception implements Stringable, Throwable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception\LoadFailed {
	class Module extends Yaf\Exception\LoadFailed implements Throwable, Stringable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception\LoadFailed {
	class Controller extends Yaf\Exception\LoadFailed implements Throwable, Stringable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception\LoadFailed {
	class Action extends Yaf\Exception\LoadFailed implements Throwable, Stringable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception\LoadFailed {
	class View extends Yaf\Exception\LoadFailed implements Throwable, Stringable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf\Exception {
	class TypeError extends Yaf\Exception implements Stringable, Throwable {
		/* properties */
		protected $file = '';
		protected $line = 0;
		protected $message = NULL;
		protected $code = 0;
		protected $previous = NULL;

		/* methods */
		public function __construct(string $message = '', int $code = 0, ?Throwable $previous = NULL) {
		}
		public function __wakeup() {
		}
		final public function getMessage() {
		}
		final public function getCode() {
		}
		final public function getFile() {
		}
		final public function getLine() {
		}
		final public function getTrace() {
		}
		final public function getPrevious() {
		}
		final public function getTraceAsString() {
		}
		public function __toString() {
		}
	}
}

namespace Yaf {
	interface View_Interface {
		/* methods */
		public function assign();
		public function display();
		public function render();
		public function setScriptPath();
		public function getScriptPath();
	}
}

namespace Yaf {
	interface Route_Interface {
		/* methods */
		public function route();
		public function assemble();
	}
}

